#ifndef CONVOLVE_SIGMA_ADD_F_CUDA_H_
#define CONVOLVE_SIGMA_ADD_F_CUDA_H_

#include <coupled_function.hpp>
#include <coupled_function_2.hpp>
#include <zisa/memory/array.hpp>

template <int n_coupled, typename Scalar, typename Function>
void convolve_sigma_add_f_cuda(zisa::array_view<Scalar, 2> dst,
                               zisa::array_const_view<Scalar, 2> src,
                               zisa::array_const_view<Scalar, 2> sigma,
                               Scalar del_x_2, Function f);

#define PDE_SOLVERS_CUDA_INSTANCIATE_CONVOLVE_SIGMA_CUDA(TYPE, N_COUPLED,      \
                                                         MAX_POT)              \
  extern template void convolve_sigma_add_f_cuda<                              \
      N_COUPLED, TYPE, CoupledFunction<TYPE, N_COUPLED, MAX_POT>>(             \
      zisa::array_view<TYPE, 2>, zisa::array_const_view<TYPE, 2>,              \
      zisa::array_const_view<TYPE, 2>, TYPE,                                   \
      CoupledFunction<TYPE, N_COUPLED, MAX_POT>);

#define PDE_SOLVERS_CUDA_INSTANCIATE_CONVOLVE_SIGMA_CUDA_2(TYPE, N_COUPLED)    \
  extern template void                                                         \
      convolve_sigma_add_f_cuda<N_COUPLED, TYPE, CoupledFunction2<TYPE>>(      \
          zisa::array_view<TYPE, 2>, zisa::array_const_view<TYPE, 2>,          \
          zisa::array_const_view<TYPE, 2>, TYPE, CoupledFunction2<TYPE>);

PDE_SOLVERS_CUDA_INSTANCIATE_CONVOLVE_SIGMA_CUDA(float, 1, 1)
PDE_SOLVERS_CUDA_INSTANCIATE_CONVOLVE_SIGMA_CUDA(double, 1, 1)
PDE_SOLVERS_CUDA_INSTANCIATE_CONVOLVE_SIGMA_CUDA(float, 2, 1)
PDE_SOLVERS_CUDA_INSTANCIATE_CONVOLVE_SIGMA_CUDA(double, 2, 1)
PDE_SOLVERS_CUDA_INSTANCIATE_CONVOLVE_SIGMA_CUDA(float, 3, 1)
PDE_SOLVERS_CUDA_INSTANCIATE_CONVOLVE_SIGMA_CUDA(double, 3, 1)
PDE_SOLVERS_CUDA_INSTANCIATE_CONVOLVE_SIGMA_CUDA(float, 4, 1)
PDE_SOLVERS_CUDA_INSTANCIATE_CONVOLVE_SIGMA_CUDA(double, 4, 1)
PDE_SOLVERS_CUDA_INSTANCIATE_CONVOLVE_SIGMA_CUDA(float, 5, 1)
PDE_SOLVERS_CUDA_INSTANCIATE_CONVOLVE_SIGMA_CUDA(double, 5, 1)
PDE_SOLVERS_CUDA_INSTANCIATE_CONVOLVE_SIGMA_CUDA(float, 1, 2)
PDE_SOLVERS_CUDA_INSTANCIATE_CONVOLVE_SIGMA_CUDA(double, 1, 2)
PDE_SOLVERS_CUDA_INSTANCIATE_CONVOLVE_SIGMA_CUDA(float, 2, 2)
PDE_SOLVERS_CUDA_INSTANCIATE_CONVOLVE_SIGMA_CUDA(double, 2, 2)
PDE_SOLVERS_CUDA_INSTANCIATE_CONVOLVE_SIGMA_CUDA(float, 3, 2)
PDE_SOLVERS_CUDA_INSTANCIATE_CONVOLVE_SIGMA_CUDA(double, 3, 2)
PDE_SOLVERS_CUDA_INSTANCIATE_CONVOLVE_SIGMA_CUDA(float, 4, 2)
PDE_SOLVERS_CUDA_INSTANCIATE_CONVOLVE_SIGMA_CUDA(double, 4, 2)
PDE_SOLVERS_CUDA_INSTANCIATE_CONVOLVE_SIGMA_CUDA(float, 5, 2)
PDE_SOLVERS_CUDA_INSTANCIATE_CONVOLVE_SIGMA_CUDA(double, 5, 2)
PDE_SOLVERS_CUDA_INSTANCIATE_CONVOLVE_SIGMA_CUDA(float, 1, 3)
PDE_SOLVERS_CUDA_INSTANCIATE_CONVOLVE_SIGMA_CUDA(double, 1, 3)
PDE_SOLVERS_CUDA_INSTANCIATE_CONVOLVE_SIGMA_CUDA(float, 2, 3)
PDE_SOLVERS_CUDA_INSTANCIATE_CONVOLVE_SIGMA_CUDA(double, 2, 3)
PDE_SOLVERS_CUDA_INSTANCIATE_CONVOLVE_SIGMA_CUDA(float, 3, 3)
PDE_SOLVERS_CUDA_INSTANCIATE_CONVOLVE_SIGMA_CUDA(double, 3, 3)
PDE_SOLVERS_CUDA_INSTANCIATE_CONVOLVE_SIGMA_CUDA(float, 4, 3)
PDE_SOLVERS_CUDA_INSTANCIATE_CONVOLVE_SIGMA_CUDA(double, 4, 3)
PDE_SOLVERS_CUDA_INSTANCIATE_CONVOLVE_SIGMA_CUDA(float, 5, 3)
PDE_SOLVERS_CUDA_INSTANCIATE_CONVOLVE_SIGMA_CUDA(double, 5, 3)
PDE_SOLVERS_CUDA_INSTANCIATE_CONVOLVE_SIGMA_CUDA(float, 1, 4)
PDE_SOLVERS_CUDA_INSTANCIATE_CONVOLVE_SIGMA_CUDA(double, 1, 4)
PDE_SOLVERS_CUDA_INSTANCIATE_CONVOLVE_SIGMA_CUDA(float, 2, 4)
PDE_SOLVERS_CUDA_INSTANCIATE_CONVOLVE_SIGMA_CUDA(double, 2, 4)
PDE_SOLVERS_CUDA_INSTANCIATE_CONVOLVE_SIGMA_CUDA(float, 3, 4)
PDE_SOLVERS_CUDA_INSTANCIATE_CONVOLVE_SIGMA_CUDA(double, 3, 4)
PDE_SOLVERS_CUDA_INSTANCIATE_CONVOLVE_SIGMA_CUDA(float, 4, 4)
PDE_SOLVERS_CUDA_INSTANCIATE_CONVOLVE_SIGMA_CUDA(double, 4, 4)
PDE_SOLVERS_CUDA_INSTANCIATE_CONVOLVE_SIGMA_CUDA(float, 5, 4)
PDE_SOLVERS_CUDA_INSTANCIATE_CONVOLVE_SIGMA_CUDA(double, 5, 4)
PDE_SOLVERS_CUDA_INSTANCIATE_CONVOLVE_SIGMA_CUDA(float, 1, 5)
PDE_SOLVERS_CUDA_INSTANCIATE_CONVOLVE_SIGMA_CUDA(double, 1, 5)
PDE_SOLVERS_CUDA_INSTANCIATE_CONVOLVE_SIGMA_CUDA(float, 2, 5)
PDE_SOLVERS_CUDA_INSTANCIATE_CONVOLVE_SIGMA_CUDA(double, 2, 5)
PDE_SOLVERS_CUDA_INSTANCIATE_CONVOLVE_SIGMA_CUDA(float, 3, 5)
PDE_SOLVERS_CUDA_INSTANCIATE_CONVOLVE_SIGMA_CUDA(double, 3, 5)
PDE_SOLVERS_CUDA_INSTANCIATE_CONVOLVE_SIGMA_CUDA(float, 4, 5)
PDE_SOLVERS_CUDA_INSTANCIATE_CONVOLVE_SIGMA_CUDA(double, 4, 5)
PDE_SOLVERS_CUDA_INSTANCIATE_CONVOLVE_SIGMA_CUDA(float, 5, 5)
PDE_SOLVERS_CUDA_INSTANCIATE_CONVOLVE_SIGMA_CUDA(double, 5, 5)


PDE_SOLVERS_CUDA_INSTANCIATE_CONVOLVE_SIGMA_CUDA_2(float, 1)
PDE_SOLVERS_CUDA_INSTANCIATE_CONVOLVE_SIGMA_CUDA_2(double, 1)
PDE_SOLVERS_CUDA_INSTANCIATE_CONVOLVE_SIGMA_CUDA_2(float, 2)
PDE_SOLVERS_CUDA_INSTANCIATE_CONVOLVE_SIGMA_CUDA_2(double, 2)
PDE_SOLVERS_CUDA_INSTANCIATE_CONVOLVE_SIGMA_CUDA_2(float, 3)
PDE_SOLVERS_CUDA_INSTANCIATE_CONVOLVE_SIGMA_CUDA_2(double, 3)
PDE_SOLVERS_CUDA_INSTANCIATE_CONVOLVE_SIGMA_CUDA_2(float, 4)
PDE_SOLVERS_CUDA_INSTANCIATE_CONVOLVE_SIGMA_CUDA_2(double, 4)
PDE_SOLVERS_CUDA_INSTANCIATE_CONVOLVE_SIGMA_CUDA_2(float, 5)
PDE_SOLVERS_CUDA_INSTANCIATE_CONVOLVE_SIGMA_CUDA_2(double, 5)

#undef PDE_SOLVERS_CUDA_INSTANCIATE_CONVOLVE_SIGMA_CUDA
#undef PDE_SOLVERS_CUDA_INSTANCIATE_CONVOLVE_SIGMA_CUDA_2

#endif
