model: "bruss"
run_type: "from_df"
run_id: "ball_int"

simulation:
  Nx: 128
  dx: 1.0
  Nt: 60000
  dt: 0.0025
  n_snapshots: 100



model_params:
  bruss:
    df_file: "data/varied_points.csv"
    initial_conditions:
      - type: "normal"
        sigma_u: 0.1
        sigma_v: 0.1
      - type: "normal"
        sigma_u: 0.25
        sigma_v: 0.25

sampling:
  num_samples: 100
  num_samples_per_ic: 1
  std:
    A: 0.1
    B: 0.1
    Du: 0.1
    Dv: 0.1

paths:
  data_dir: "${DATA_DIR}" 